#!/usr/bin/env bash
# This script configures Nginx with a custom HTTP response header
apt-get update -y
apt-get install nginx -y
echo 'Holberton School' > /var/www/html/index.html
HOSTNAME=$(hostname)
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default
service nginx restart