#!/usr/bin/env bash
# This script installs and configures HAProxy load balancer
apt-get update -y
apt-get install haproxy -y
tee /etc/haproxy/haproxy.cfg << 'EOF'
global
    log /dev/log local0
    maxconn 2048
    user haproxy
    group haproxy
    daemon
defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000
    timeout client 50000
    timeout server 50000
frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server web-01 52.91.114.189:80 check
    server web-02 44.204.154.218:80 check
EOF
service haproxy restart