#!/usr/bin/env bash
# This script installs and configures Nginx web server
apt-get update -y
apt-get install nginx -y
rm /var/www/html/index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.html
nginx -s reload