#!/usr/bin/env bash
# This script configures Nginx with a 301 redirect
apt-get update -y
apt-get install nginx -y
echo 'Holberton School' > /var/www/html/index.html
printf 'server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm;\n\tserver_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\tlocation / {\n\t\ttry_files \ \/ =404;\n\t}\n}' > /etc/nginx/sites-available/default
service nginx restart