#!/usr/bin/env bash
# This script configures Nginx with a 301 redirect
apt-get update -y
apt-get install nginx -y
echo 'Holberton School' > /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/' /etc/nginx/sites-available/default
service nginx restart