#!/usr/bin/env bash
# This script configures Nginx with a custom 404 page
apt-get update -y
apt-get install nginx -y
echo 'Holberton School' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i 's/server_name _;/server_name _;\n\terror_page 404 \/404.html;/' /etc/nginx/sites-available/default
service nginx restart